package com.app.controller;



import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.util.FileCopyUtils;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

import com.app.model.Document;
import com.app.service.IDocumentService;

@Controller
@RequestMapping("/docs")
public class DocumentController {
	@Autowired
	private IDocumentService service;
	
	//1. show Document Page
	@RequestMapping("/all")
	public String showDocs(ModelMap m) {
		
		List<Object[]> list=service.getDocsIdAndName();
		m.addAttribute("list",list);
		return "Documents";
		
		
	}
	
	//2. on click upload
	@RequestMapping(value="/upload",method=RequestMethod.POST)
	
	public String uploadDoc(@RequestParam("fileObj") CommonsMultipartFile file,ModelMap m) {
		if(file!=null) {
			//convert CMF data to modelclass object
			Document doc = new Document();
			//doc.setFileId(fileId);autogenerated
			doc.setFileName(file.getOriginalFilename());
			doc.setFileData(file.getBytes());
			
			int id = service.saveDocument(doc);
			String msg="saved with id"+id;
			m.addAttribute("message",msg);
			
			List<Object[]> list=service.getDocsIdAndName();
			m.addAttribute("list",list);
			
			
	
		}
		
		return "Documents";
	}
	//3 download document
	@RequestMapping("/download")
	public void downloadDoc(@RequestParam Integer docId , HttpServletResponse res) {
		
	Document doc = service.getDocumentById(docId);
	res.addHeader("Content-Disposition", "attachment;filename="+doc.getFileName());
	try {
		FileCopyUtils.copy(doc.getFileData(), res.getOutputStream());
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	
	
	
	}
	
	
	
	
	
	
	
}
